apiVersion: batch/v1
kind: Job
metadata:
  name: example-job
spec:
  backoffLimit: 3
  activeDeadLineSeconds: 58
  completions: 3
  parallelism: 2
  template:
    spec: 
      containers: 
        -  name: example-container 
           image: alpine
           command: ["sh" ,"-c","echo 'Started' && sleep 10 && exit 1"]
           restartPolicy: Never
